services:
  api:
    build:
      context: ./api
    container_name: dog-classifier-api
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./ui
    container_name: dog-classifier-ui
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=/api/predict

  proxy:
    image: nginx:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - frontend
