import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { LanguageProvider } from "@/contexts/LanguageContext";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
      />
      <LanguageProvider>
        <body className={`${poppins.className} bg-bg cursor-default`}>
          <Header />
          <div className="min-h-[calc(100vh-192px)] lg:min-h-[calc(100vh-213px)]">
            {children}
          </div>
          <Footer />
        </body>
      </LanguageProvider>
    </html>
  );
}
