services:
  frontend:
    build: .
    container_name: "dog-classifier-ui-container"
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api/predict
