name: Build, Push to ECR, and Deploy to Lightsail

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push API image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/${{ secrets.ECR_REPOSITORY_API }}:$IMAGE_TAG -t $ECR_REGISTRY/${{ secrets.ECR_REPOSITORY_API }}:latest ./api
          docker push $ECR_REGISTRY/${{ secrets.ECR_REPOSITORY_API }}:$IMAGE_TAG
          docker push $ECR_REGISTRY/${{ secrets.ECR_REPOSITORY_API }}:latest

      - name: Build, tag, and push UI image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/${{ secrets.ECR_REPOSITORY_UI }}:$IMAGE_TAG -t $ECR_REGISTRY/${{ secrets.ECR_REPOSITORY_UI }}:latest --build-arg NEXT_PUBLIC_API_URL=/api ./ui
          docker push $ECR_REGISTRY/${{ secrets.ECR_REPOSITORY_UI }}:$IMAGE_TAG
          docker push $ECR_REGISTRY/${{ secrets.ECR_REPOSITORY_UI }}:latest

  deploy-to-lightsail:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Lightsail instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_SSH_HOST }}
          username: ${{ secrets.LIGHTSAIL_SSH_USERNAME }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            cd ~/ai-image-dogs-classifier

            git pull origin main

            cat > .env << EOF
            ECR_REGISTRY=${{ secrets.ECR_REGISTRY }}
            ECR_REPOSITORY_API=${{ secrets.ECR_REPOSITORY_API }}
            ECR_REPOSITORY_UI=${{ secrets.ECR_REPOSITORY_UI }}
            EOF

            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws configure set region ${{ secrets.AWS_REGION }}

            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

            docker-compose down

            docker image prune -af

            docker-compose pull

            docker-compose up -d --force-recreate

            echo ">>> Deployment to Lightsail finished successfully! <<<"
